### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Marken23** [wangcongcong123/auto_coding#2]
It's just like a search task, it's not generating any code, just search for the appropriate code and return it, right or I got the idea wrong?

**Comment by wangcongcong123** [comment]
I would say it is making predictions on the previous tokens in a sequence, so called casual language modelling in GPT-2. Assume you have context code `def factorial` as input, then the model predicts and outputs what comes next based on what it learned from the training set.  Unlike a search task, it matches a query to all indexed documents (code snippets here) and return the ones with the most relevance to the query. I'd like to point to [this blog](https://wangcongcong123.github.io/AutoCoder/) for more details.

**Comment by cameronbergh** [comment]
@Marken23 since this is based on the GPT-2 language model, id recommend looking up GPT-2 and GPT-3, there is much work being done to determine if these models are reasoning or just memorizing, and i think its a little of both. id recommend this article as well: (https://towardsdatascience.com/openai-gpt-2-understanding-language-generation-through-visualization-8252f683b2f8).
